### ISSUE TITLE
Avoid using a non-standard license

### ISSUE THREAD

**Issue by ideasman42** [duckwork/titlecase.el#10]
Strongly suggest to use a standard license, and include the LICENSE file in the repository.

While I understand the inclination to use something brief and easy to understand, this complicates sharing code with other projects.
My recent pull request to add tests for example I took code from another project which uses the GPL since that's common for Emacs/Lisp projects as it allows sharing code with Emacs it's self, having to worry about re-licensing / dual-licensing introduces unnecessary friction in my opinion.

**Comment by duckwork** [comment]
Haha, I saw that on your test PR :)

You know, you're right about this. Thanks for including the License file in the PR for the tests; I'll just merge that then update the license elsewhere to reflect it.
