### ISSUE TITLE
Add to Non-GNU Elpa

### ISSUE THREAD

**Issue by duckwork** [duckwork/titlecase.el#19]
Possibly also MELPA.

**Comment by ideasman42** [comment]
Are there any blocks for this?

**Comment by duckwork** [comment]
I've submitted [PR  #7852](https://github.com/melpa/melpa/pull/7852) to MELPA.

**Comment by duckwork** [comment]
Since we are now on MELPA, I'm closing this issue. I might still add `titlecase` to Non-GNU ELPA, or you're welcome to as well @ideasman42.
