### ISSUE TITLE
Suggestion: remove duplicate information from readme/source-code

### ISSUE THREAD

**Issue by ideasman42** [duckwork/titlecase.el#23]
Currently `titlecase.el` duplicates a lot of information in `README.org`,
there were some minor typos corrected in `titlecase.el` that have not been applied to `README.org`.

In general I find duplicating information like this not to be all that helpful (typically gets out of sync then is more hassle to maintain).

Suggest to:
- Keep implementation details in the source.
- Keep details the user might want to know about in the readme.
- Keep duplicate information to a minimum.

**Comment by duckwork** [comment]
Okay I've done it. I think we're about ready to bump another version, but I want to let this rest for a day or two before hand.

I've also done a lot of other user-facing changes too :)
