### ISSUE TITLE
Cursor moves around unexpectedly when undoing and redoing

### ISSUE THREAD

**Issue by SimonGZ** [duckwork/titlecase.el#26]
Loving these functions! One tiny issue...

If I titlecase something, then hit undo, the cursor ends up in expected places.

If I have the following...
`quick |start guide`
...and my cursor is right before "s", then I hit M-x titlecase-line... 
`Quick |Start Guide`
And the cursor correctly stays in the same spot. But if I then decide I don't actually want it to be titlecase, so I undo...
`quick start guide|`
my cursor will jump to the end of the line rather than staying before the s. 

Then if I redo, the cursor jumps back a word:
`Quick Start |Guide`

**Comment by duckwork** [comment]
I wonder if it'd be acceptable to you to just have the cursor move to the end of the line or region when title-casing? I suspect (I have yet to confirm) that the undo-complication might be why many Emacs commands move to the end of the region when changing text.

**Comment by SimonGZ** [comment]
Ideally it would return to the same spot but I agree that if it went to the end of the line or region when run then the undo wouldn’t be leaving the cursor in an unexpected place, which is what makes the behavior stand out right now.

**Comment by duckwork** [comment]
I think this is the best I can do -- `titlecase-region` is able to stay in the same spot, but `titlecase-line` and `titlecase-sentence` move to the end of their respective things after titlecasing. Honestly this is more in-line with Emacs's other case-twiddling functions, so I think it makes sense. Undoing these should move to their respective thing's beginnings.

**Comment by duckwork** [comment]
Sorry, see [this commit](https://github.com/duckwork/titlecase.el/commit/cc3b6b2d7d83b06fe88c0bc0af20cc9e4fe2b8e9). I was trying to mention this issue in the commit message but the `#` started a line, leading to a comment >.<
