### ISSUE TITLE
Embark binding

### ISSUE THREAD

**Issue by minad** [duckwork/titlecase.el#28]
Hey @duckwork,

thanks for this interesting and useful package! This is not really an issue and I am also not sure if you're using [Embark](https://github.com/oantolin/embark), but there I bind `titlecase-line` to `t` in the `embark-heading-map`. Furthermore `titlecase-region` could go to the `embark-region-map`. Maybe that's a useful tip for the README? In any case I added some documentation to the [Embark wiki](https://github.com/oantolin/embark/wiki/Additional-Actions#heading-actions).

**Comment by duckwork** [comment]
Hey @minad !

I'm glad you're getting use out of it. I do use Embark and it's a great idea. I'll add the documentation from Embark to titlecase's README :)

**Comment by hmelman** [comment]
I suggest changing this suggestion to use `T` instead of `t`.  In the `embark-region-map` `t` is already bound to `transpose-regions` and this matches other transpose bindings in embark. `T` is otherwise unbound in embark.

**Comment by duckwork** [comment]
Makes sense, changed! Thanks.
