### ISSUE TITLE
Add Support for an IMDb Style

### ISSUE THREAD

**Issue by hmelman** [duckwork/titlecase.el#32]
I think I would use an IMDb style as described [here](https://help.imdb.com/article/contribution/titles/title-formatting/G56U5ERK7YY47CQB#).  I think it's basically NYT with a different set of words.

**Comment by duckwork** [comment]
I'm not seeing anything under the "Capitalization and character sets" section; could you point out the specific rules you're talking about?

**Comment by hmelman** [comment]
In Examples:

> For English, Portuguese, Hebrew, Indian languages - these should all have capital letters at the start of words, with a few exceptions:
> English language words which must begin with a lower-case letter (unless at the end of a title) are: a an and as at by for from in of on or the to with

**Comment by duckwork** [comment]
Ahhh, I see. Thanks for the help --- this website gives me a headache, lol. I'll get a patch up ... soon!

**Comment by duckwork** [comment]
Should be good to go, let me know what you think. Also development has moved to https://codeberg.org/acdw/titlecase.el; I'll be archiving all my Github repos soon!

**Comment by hmelman** [comment]
That's great thanks!.  FYI, it's usually written as IMDb not IMDB.
