### ISSUE TITLE
Contractions are mis-capitalized

### ISSUE THREAD

**Issue by duckwork** [duckwork/titlecase.el#4]
From [u/MmmCurry](https://old.reddit.com/r/emacs/comments/rpe8us/ann_titlecaseel_titlecase_things_in_emacs/hq4k4fk/?context=3):

> Test case I tried: "i can't live with or without you"
> Result (default Chicago style): "I Can'T Live with or without You"

**Comment by ideasman42** [comment]
In case it helps, my answer on SE handles this and could be used as a reference.

https://emacs.stackexchange.com/a/66362/2418

**Comment by duckwork** [comment]
Thanks @ideasman42 , it helped quite a bit :)
